/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.REACT_APP_PROJECT_REGION,
    "aws_cognito_identity_pool_id": process.env.REACT_APP_COGNITO_IDENTITYPOOLID,
    "aws_cognito_region": process.env.REACT_APP_PROJECT_REGION,
    "aws_user_pools_id": process.env.REACT_APP_USER_POOLSID,
    "aws_user_pools_web_client_id": process.env.REACT_APP_USER_POOLSID_WEBCLIENTID,
    "oauth": {},
    "aws_appsync_graphqlEndpoint": process.env.REACT_APP_APPSYNC_GRAPHQLENDPOINT,
    "aws_appsync_region": process.env.REACT_APP_PROJECT_REGION,
    "aws_appsync_authenticationType": process.env.REACT_APP_APPSYNC_AUTHENTICATIONTYPE
};


export default awsmobile;
