/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:609df095-e8c5-475a-989a-df2b079a844e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_BLKHYMWjK",
    "aws_user_pools_web_client_id": "7ljldthlpj2e8s192ktit9kgh2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5mubn4wgrbfbpf5pigxfcrwopa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
